### ISSUE TITLE
拉取到本地 无法通过编译

### ISSUE THREAD

**Issue by cooek** [merry1997/iCloudMusic#2]
大佬 拉取后无法通过编译！大佬

**Comment by cooek** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.8.2/lib/flushbar.dart:266:3: Error: Type 'FocusAttachment' not found.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.8.2/lib/flushbar.dart:266:3: Error: 'FocusAttachment' isn't a type.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.8.2/lib/flushbar.dart:287:35: Error: The method 'attach' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///D:/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'attach'.
    _focusAttachment = _focusNode.attach(context);
                                  ^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.8.2/lib/flushbar.dart:298:16: Error: The method 'dispose' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///D:/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dispose'.
    _focusNode.dispose();
               ^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.4/lib/flare.dart:1027:18: Error: The argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on C:\Users\HP\Desktop\iCloudMusic-master\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Xbs233** [comment]
不通过+1
```
Compiler message:
/users/flutter/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.1/lib/flare
.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the
parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on /Users/xbs/Desktop/flutterProject/iCloudMusic/lib/main.dart
Error launching application on iPhone 11 Pro Max.
```

**Comment by xiongjx** [comment]
同上+1
flutter 1.9.1+hotfix.1

**Comment by xiongjx** [comment]
pubspec.yaml修改 flare_flutter:^1.5.4 即可编译安装，安装完成后加载首页动画后崩溃

**Comment by Xbs233** [comment]
> pubspec.yaml修改 flare_flutter:^1.5.4 即可编译安装，安装完成后加载首页动画后崩溃

你试下在ios环境下安装，我ios下正常了，android下好像因为androidx相关的一些问题，debug可以安装，但是会崩溃，release无法安装，提示androidx相关错误

**Comment by xiongjx** [comment]
没有ios环境




------------------ 原始邮件 ------------------
发件人: "a747368836"<notifications@github.com>; 
发送时间: 2019年10月8日(星期二) 凌晨0:13
收件人: "monako97/iCloudMusic"<iCloudMusic@noreply.github.com>; 
抄送: "Panda"<xiongjianx@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [monako97/iCloudMusic] 拉取到本地 无法通过编译 (#2)



 
pubspec.yaml修改 flare_flutter:^1.5.4 即可编译安装，安装完成后加载首页动画后崩溃
  
你试下在ios环境下安装，我ios下正常了，android下好像因为androidx相关的一些问题，debug可以安装，但是会崩溃，release无法安装，提示androidx相关错误

**Comment by moneko-o** [comment]
旧版本的包导致的，已修复
